# .github/workflows/test.yml
name: Test API
# When it's trigger
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Repo
      run: git clone https://github.com/KhievSothy/devops-cadt-2-main.git
      - name: List folders
      run: ls